In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Load the data

In [2]:
try:
    data = pd.read_excel('Copy of RI INDEX Q4 2017.xlsx')
except OSError as error:
    print("Error: ", error)

#### Set the maximum columns display to 30

In [3]:
pd.options.display.max_columns = 30

#### Display the data

In [4]:
data.head(10)

,Unnamed: 0,Unnamed: 1,Q1 - 2016 (N),Q2 - 2016 (N),Q3 - 2016 (N),Q4 - 2016 (N),Q1 - 2017 (N),Q2 - 2017 (N),Q3 - 2017 (N),Q4 - 2017 (N),INDEX Q1 - 2016 (BASE PERIOD),INDEX Q2 - 2016,INDEX Q3 - 2016,INDEX Q4 - 2016,INDEX Q1 - 2017,INDEX Q2 - 2017,INDEX Q3- 2017,INDEX Q4- 2017,PRICE CHANGE Q2 - 2016 (%),PRICE CHANGE Q3 - 2016 (%),PRICE CHANGE Q4 - 2016 (%),PRICE CHANGE Q1 - 2017 (%),PRICE CHANGE Q2 - 2017 (%),PRICE CHANGE Q3 - 2017 (%),PRICE CHANGE Q4 - 2017 (%)
0,Agege,5 Bedroom,4.397350e+07,4.150000e+07,4.125000e+07,4.211764e+07,3.850000e+07,34000000.0,34055555.0,3.150000e+07,100.0,94.375021,93.806497,95.779592,87.552731,77.319295,77.445632,71.634052,-5.624979,-0.602410,2.103367,-8.589368,-11.688312,0.163397,-7.504077
1,NaN,4 Bedroom,3.750000e+07,3.800000e+07,3.745000e+07,3.850000e+07,2.750000e+07,25500000.0,26033555.0,2.603356e+07,100.0,101.333333,99.866667,102.666667,73.333333,68.000000,69.422813,69.422813,1.333333,-1.447368,2.803738,-28.571429,-7.272727,2.092373,0.000000
2,NaN,3 Bedroom,1.932000e+07,1.875000e+07,1.750000e+07,1.757550e+07,1.600000e+07,16655000.0,16655000.0,1.573899e+07,100.0,97.049689,90.579710,90.970497,82.815735,86.206004,86.206004,81.464742,-2.950311,-6.666667,0.431429,-8.964183,4.093750,0.000000,-5.499921
3,NaN,2 Bedroom,1.163458e+07,1.078623e+07,9.937875e+06,9.574290e+06,8.483553e+06,8975500.0,8255555.0,7.348489e+06,100.0,92.708335,85.416669,82.291633,72.916679,77.144995,70.957022,63.160731,-7.291665,-7.865167,-3.658579,-11.392354,5.798832,-8.021224,-10.987343
4,Ajah,5 Bedroom,4.430709e+07,3.500000e+07,3.900000e+07,5.000000e+07,5.500000e+07,53565500.0,52833333.0,5.200000e+07,100.0,78.994135,88.022036,112.848764,124.133640,120.896009,119.243526,117.362714,-21.005865,11.428571,28.205128,10.000000,-2.608182,-1.366863,-1.577286
5,NaN,4 Bedroom,3.631651e+07,2.654300e+07,3.300000e+07,3.500000e+07,3.150000e+07,32450500.0,39100000.0,4.150000e+07,100.0,73.087962,90.867752,96.374889,86.737400,89.354667,107.664519,114.273082,-26.912038,24.326564,6.060606,-10.000000,3.017460,20.491210,6.138107
6,NaN,3 Bedroom,2.663946e+07,2.200000e+07,2.750000e+07,3.000000e+07,2.166667e+07,21950500.0,29466667.0,3.150000e+07,100.0,82.584269,103.230336,112.614912,81.332993,82.398454,110.612871,118.245658,-17.415731,25.000000,9.090909,-27.777777,1.309998,34.241439,6.900451
7,NaN,2 Bedroom,1.685837e+07,1.617027e+07,1.445003e+07,1.634230e+07,1.552518e+07,16435500.0,23500000.0,2.400000e+07,100.0,95.918367,85.714286,96.938776,92.091837,97.491636,139.396639,142.362524,-4.081633,-10.638298,13.095238,-5.000000,5.863494,42.983177,2.127660
8,Gbagada,5 Bedroom,5.160000e+07,4.534550e+07,6.500000e+07,7.000000e+07,8.125000e+07,78365550.0,62250000.0,6.225000e+07,100.0,87.878876,125.968992,135.658915,157.461240,151.871221,120.639535,120.639535,-12.121124,43.343882,7.692308,16.071429,-3.550092,-20.564585,0.000000
9,NaN,4 Bedroom,5.000000e+07,4.150000e+07,4.250000e+07,5.500000e+07,6.125000e+07,63255500.0,63255500.0,6.325550e+07,100.0,83.000000,85.000000,110.000000,122.500000,126.511000,126.511000,126.511000,-17.000000,2.409639,29.411765,11.363636,3.274286,0.000000,0.000000

In [5]:
data.tail(10)

,Unnamed: 0,Unnamed: 1,Q1 - 2016 (N),Q2 - 2016 (N),Q3 - 2016 (N),Q4 - 2016 (N),Q1 - 2017 (N),Q2 - 2017 (N),Q3 - 2017 (N),Q4 - 2017 (N),INDEX Q1 - 2016 (BASE PERIOD),INDEX Q2 - 2016,INDEX Q3 - 2016,INDEX Q4 - 2016,INDEX Q1 - 2017,INDEX Q2 - 2017,INDEX Q3- 2017,INDEX Q4- 2017,PRICE CHANGE Q2 - 2016 (%),PRICE CHANGE Q3 - 2016 (%),PRICE CHANGE Q4 - 2016 (%),PRICE CHANGE Q1 - 2017 (%),PRICE CHANGE Q2 - 2017 (%),PRICE CHANGE Q3 - 2017 (%),PRICE CHANGE Q4 - 2017 (%)
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
!pip install xlrd

WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the 'c:\users\zeliha\appdata\local\programs\python\python38-32\python.exe -m pip install --upgrade pip' command.

Collecting xlrd
  Downloading xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Installing collected packages: xlrd
Successfully installed xlrd-1.2.0

In [6]:
data.sample(10)

,Unnamed: 0,Unnamed: 1,Q1 - 2016 (N),Q2 - 2016 (N),Q3 - 2016 (N),Q4 - 2016 (N),Q1 - 2017 (N),Q2 - 2017 (N),Q3 - 2017 (N),Q4 - 2017 (N),INDEX Q1 - 2016 (BASE PERIOD),INDEX Q2 - 2016,INDEX Q3 - 2016,INDEX Q4 - 2016,INDEX Q1 - 2017,INDEX Q2 - 2017,INDEX Q3- 2017,INDEX Q4- 2017,PRICE CHANGE Q2 - 2016 (%),PRICE CHANGE Q3 - 2016 (%),PRICE CHANGE Q4 - 2016 (%),PRICE CHANGE Q1 - 2017 (%),PRICE CHANGE Q2 - 2017 (%),PRICE CHANGE Q3 - 2017 (%),PRICE CHANGE Q4 - 2017 (%)
12,Ibeju-Lekki,5 Bedroom,4.500000e+07,4.600000e+07,4.100000e+07,4.100000e+07,3.850000e+07,40450667.0,4.016667e+07,4.016667e+07,100.0,102.222222,91.111111,91.111111,85.555556,89.890371,89.259260,89.259260,2.222222,-10.869565,0.000000,-6.097561,5.066668,-0.702090,0.000000
55,NaN,2 Bedroom,2.370743e+07,2.204791e+07,1.991424e+07,2.183227e+07,2.199065e+07,22765650.0,2.425000e+07,2.427319e+07,100.0,93.000000,84.000000,92.090439,92.758490,96.027508,102.288627,102.386459,-7.000000,-9.677419,9.631474,0.725430,3.524225,6.520130,0.095643
43,NaN,2 Bedroom,1.918566e+07,1.959735e+07,1.792583e+07,1.738806e+07,1.686642e+07,17656667.0,1.966667e+07,1.968548e+07,100.0,102.145803,93.433488,90.630483,87.911568,92.030526,102.507099,102.605140,2.145803,-8.529293,-3.000000,-3.000000,4.685342,11.383802,0.095643
33,NaN,4 Bedroom,6.416346e+07,5.300000e+07,6.250000e+07,6.133333e+07,5.750000e+07,60666667.0,5.671625e+07,5.877050e+07,100.0,82.601528,97.407462,95.589189,89.614865,94.550177,88.393376,91.594957,-17.398472,17.924528,-1.866667,-6.249999,5.507247,-6.511676,3.621970
58,NaN,3 Bedroom,4.637588e+07,3.100000e+07,3.000000e+07,3.300000e+07,3.300000e+07,35250500.0,3.645863e+07,3.849350e+07,100.0,66.845088,64.688795,71.157675,71.157675,76.010413,78.615490,83.003267,-33.154912,-3.225806,10.000000,0.000000,6.819697,3.427264,5.581313
36,Maryland,5 Bedroom,1.077419e+08,1.070000e+08,1.200000e+08,1.300000e+08,1.193333e+08,121650500.0,1.233333e+08,1.194513e+08,100.0,99.311378,111.377246,120.658683,110.758483,112.909147,114.471058,110.867967,-0.688622,12.149533,8.333333,-8.205128,1.941760,1.383334,-3.147600
0,Agege,5 Bedroom,4.397350e+07,4.150000e+07,4.125000e+07,4.211764e+07,3.850000e+07,34000000.0,3.405556e+07,3.150000e+07,100.0,94.375021,93.806497,95.779592,87.552731,77.319295,77.445632,71.634052,-5.624979,-0.602410,2.103367,-8.589368,-11.688312,0.163397,-7.504077
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,2 Bedroom,1.040016e+08,1.016026e+08,9.864326e+07,9.215000e+07,9.407500e+07,96500000.0,9.416667e+07,9.425673e+07,100.0,97.693300,94.847864,88.604439,90.455372,92.787068,90.543512,90.630111,-2.306700,-2.912621,-6.582568,2.088985,2.577731,-2.417962,0.095643

# Note:
formula for price change
price change

# Rename the columns

### check the column names

In [7]:
print(*data.columns, sep = '\n')

Unnamed: 0
Unnamed: 1
Q1 - 2016 (N)
Q2 - 2016 (N)
Q3 - 2016 (N)
Q4 - 2016            (N)
Q1 - 2017 (N)
Q2 - 2017 (N)
Q3 - 2017 (N)
Q4 - 2017 (N)
INDEX          Q1 - 2016 (BASE PERIOD)
INDEX          Q2 - 2016
INDEX          Q3 - 2016
INDEX          Q4 - 2016
INDEX          Q1 - 2017
INDEX          Q2 - 2017
INDEX          Q3- 2017
INDEX          Q4- 2017
PRICE CHANGE Q2 - 2016 (%)
PRICE CHANGE Q3 - 2016 (%)
PRICE CHANGE Q4 - 2016 (%)
PRICE CHANGE       Q1 - 2017 (%)
PRICE CHANGE       Q2 - 2017 (%)
PRICE CHANGE       Q3 - 2017 (%)
PRICE CHANGE       Q4 - 2017 (%)

In [42]:
columns_dict = {'Unnamed: 0' :'LGA',
'Unnamed: 1' : 'No_of_bedrooms',
'Q1 - 2016 (N)' : 'Q1_2016',
'Q2 - 2016 (N)': 'Q2_2016',
'Q3 - 2016 (N)': 'Q3_2016',
'Q4 - 2016            (N)' : 'Q4_2016',
'Q1 - 2017 (N)' : 'Q1_2017',
'Q2 - 2017 (N)': 'Q2_2017',
'Q3 - 2017 (N)' : 'Q3_2017',
'Q4 - 2017 (N)': 'Q4_2017',
'INDEX          Q1 - 2016 (BASE PERIOD)' : 'index_Q1_2016',
'INDEX          Q2 - 2016' : 'index_Q2_2016',
'INDEX          Q3 - 2016' : 'index_Q3_2016',
'INDEX          Q4 - 2016' : 'index_Q4_2016',
'INDEX          Q1 - 2017' : 'index_Q1_2017',
'INDEX          Q2 - 2017' : 'index_Q2_2017',
'INDEX          Q3- 2017' : 'index_Q3_2017',
'INDEX          Q4- 2017' : 'index_Q4_2017',
'PRICE CHANGE Q2 - 2016 (%)' : 'price_change_Q2_2016',
'PRICE CHANGE Q3 - 2016 (%)': 'price_change_Q3_2016',
'PRICE CHANGE Q4 - 2016 (%)':  'price_change_Q4_2016',
'PRICE CHANGE       Q1 - 2017 (%)' : 'price_change_Q1_2017',
'PRICE CHANGE       Q2 - 2017 (%)' : 'price_change_Q2_2017',
'PRICE CHANGE       Q3 - 2017 (%)' : 'price_change_Q3_2017',
'PRICE CHANGE       Q4 - 2017 (%)'  : 'price_change_Q4_2017'
}

#### Rename the columns

In [43]:
data.rename(columns = columns_dict, inplace = True)

#### Drop the empty cells on the sheet

In [10]:
data = data.iloc[0:60, :]

data.head(5)

,LGA,No_of_bedrooms,Q1_2016,Q2_2016,Q3_2016,Q4 - 2016 (N),Q1_2017,Q2_2017,Q3_2017,Q4_2017,index_Q1_2016,index_Q2_2016,index_Q3_2016,index_Q4_2016,index_Q1_2017,index_Q2_2017,index_Q3_2017,index_Q4_2017,price_change_Q2_2016,price_change_Q3_2016,price_change_Q4_2016,price_change_Q1_2017,price_change_Q2_2017,price_change_Q3_2017,price_change_Q4_2017
0,Agege,5 Bedroom,43973500.0,41500000.0,41250000.0,42117639.0,3.850000e+07,34000000.0,34055555.0,3.150000e+07,100.0,94.375021,93.806497,95.779592,87.552731,77.319295,77.445632,71.634052,-5.624979,-0.602410,2.103367,-8.589368,-11.688312,0.163397,-7.504077
1,NaN,4 Bedroom,37500000.0,38000000.0,37450000.0,38500000.0,2.750000e+07,25500000.0,26033555.0,2.603356e+07,100.0,101.333333,99.866667,102.666667,73.333333,68.000000,69.422813,69.422813,1.333333,-1.447368,2.803738,-28.571429,-7.272727,2.092373,0.000000
2,NaN,3 Bedroom,19320000.0,18750000.0,17500000.0,17575500.0,1.600000e+07,16655000.0,16655000.0,1.573899e+07,100.0,97.049689,90.579710,90.970497,82.815735,86.206004,86.206004,81.464742,-2.950311,-6.666667,0.431429,-8.964183,4.093750,0.000000,-5.499921
3,NaN,2 Bedroom,11634585.0,10786230.0,9937875.0,9574290.0,8.483553e+06,8975500.0,8255555.0,7.348489e+06,100.0,92.708335,85.416669,82.291633,72.916679,77.144995,70.957022,63.160731,-7.291665,-7.865167,-3.658579,-11.392354,5.798832,-8.021224,-10.987343
4,Ajah,5 Bedroom,44307087.0,35000000.0,39000000.0,50000000.0,5.500000e+07,53565500.0,52833333.0,5.200000e+07,100.0,78.994135,88.022036,112.848764,124.133640,120.896009,119.243526,117.362714,-21.005865,11.428571,28.205128,10.000000,-2.608182,-1.366863,-1.577286

### Analytical summary of the dataset

In [11]:
data.describe(include='all')

,LGA,No_of_bedrooms,Q1_2016,Q2_2016,Q3_2016,Q4 - 2016 (N),Q1_2017,Q2_2017,Q3_2017,Q4_2017,index_Q1_2016,index_Q2_2016,index_Q3_2016,index_Q4_2016,index_Q1_2017,index_Q2_2017,index_Q3_2017,index_Q4_2017,price_change_Q2_2016,price_change_Q3_2016,price_change_Q4_2016,price_change_Q1_2017,price_change_Q2_2017,price_change_Q3_2017,price_change_Q4_2017
count,15,60,6.000000e+01,6.000000e+01,6.000000e+01,6.000000e+01,6.000000e+01,6.000000e+01,6.000000e+01,5.900000e+01,60.0,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
unique,15,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,ALL CITIES,3 Bedroom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,5.420253e+07,5.034458e+07,5.726085e+07,5.717412e+07,5.252584e+07,5.393815e+07,5.528606e+07,5.626767e+07,100.0,93.958498,99.405207,99.777765,93.285209,96.157197,97.993262,97.173488,-6.041502,6.887748,0.845520,-6.026583,3.608447,2.056778,-0.919925
std,NaN,NaN,3.926180e+07,3.569327e+07,5.269530e+07,5.212501e+07,4.470348e+07,4.470556e+07,4.900402e+07,4.951364e+07,0.0,12.967853,18.206253,18.113036,17.276591,16.194228,18.028352,22.490436,12.967853,20.163589,9.697611,10.060823,8.379108,11.119247,13.604887
min,NaN,NaN,1.163458e+07,1.078623e+07,9.937875e+06,9.574290e+06,8.483553e+06,8.975500e+06,8.255555e+06,7.348489e+06,100.0,61.207202,64.688795,61.766785,55.948175,61.567610,45.321253,0.000000,-38.792798,-32.400000,-23.333333,-28.571429,-22.972973,-20.564585,-100.000000
25%,NaN,NaN,2.707599e+07,2.488632e+07,2.669314e+07,2.816642e+07,2.208975e+07,2.265560e+07,2.558767e+07,2.801678e+07,100.0,85.984780,87.875000,89.006428,82.640323,84.757002,86.966837,88.504697,-14.015220,-5.045247,-4.995768,-11.059715,1.299400,-2.737809,0.071732
50%,NaN,NaN,4.465354e+07,4.020860e+07,4.000000e+07,4.055300e+07,3.741667e+07,3.927528e+07,3.963333e+07,4.053874e+07,100.0,95.816327,94.046106,95.322549,89.045521,95.144012,97.862103,98.060413,-4.183673,0.196078,0.600330,-6.173780,3.267351,1.258270,0.095643
75%,NaN,NaN,6.437260e+07,5.662500e+07,6.425000e+07,6.555142e+07,6.175000e+07,6.391050e+07,6.242625e+07,6.300005e+07,100.0,101.477520,105.711411,109.212062,99.262524,107.108716,107.987481,108.680054,1.477520,15.129340,5.800866,-2.164704,5.814998,6.137533,1.895400
max,NaN,NaN,2.276842e+08,1.650000e+08,3.150000e+08,3.250000e+08,2.750000e+08,2.600000e+08,2.938333e+08,2.991144e+08,100.0,129.843923,150.000000,157.894737,157.461240,151.871221,140.942243,142.362524,29.843923,90.909091,29.411765,31.524866,35.370370,42.983177,13.541021

## Check the columns with null values

In [44]:
data.isnull().sum()

LGA                     0
No_of_bedrooms          0
Q1_2016                 0
Q2_2016                 0
Q3_2016                 0
Q4_2016                 0
Q1_2017                 0
Q2_2017                 0
Q3_2017                 0
Q4_2017                 1
index_Q1_2016           0
index_Q2_2016           0
index_Q3_2016           0
index_Q4_2016           0
index_Q1_2017           0
index_Q2_2017           0
index_Q3_2017           0
index_Q4_2017           0
price_change_Q2_2016    0
price_change_Q3_2016    0
price_change_Q4_2016    0
price_change_Q1_2017    0
price_change_Q2_2017    0
price_change_Q3_2017    0
price_change_Q4_2017    0
dtype: int64

#### Get the number of features and the number of samples recorded

In [13]:
print('The total samples recored: {}\nThe total number of features: {}'. format(data.shape[0], data.shape[1]))

The total samples recored: 60
The total number of features: 25

#### Check columns with missing values

In [14]:
missing_data = data.columns[data.isnull().any()].tolist()

In [15]:
print(*missing_data, sep = '\n')

LGA
Q4_2017

#### Total number of missing values

In [16]:
print('Total number of missing values:',data.isnull().sum().sum())

Total number of missing values: 46

#### The number of bedrooms

In [24]:
No_of_bedrooms = data['No_of_bedrooms'].unique()

print(*No_of_bedrooms, sep = '\n')

5 Bedroom
4 Bedroom
3 Bedroom
2 Bedroom

### Available LGAs

In [26]:
print(*data['LGA'].unique(), sep = '\n')

Agege
nan
Ajah
Gbagada
Ibeju-Lekki
Ikeja
Ikoyi
Isolo
Lekki
Magodo
Maryland
Ojodu
Surulere
Victoria Island
Yaba
ALL CITIES

## Label the missing data in the LGA column

In [28]:
data.loc[0:3, "LGA"] = 'Agege'
data.loc[4:7, "LGA"] = 'Ajah'
data.loc[8:11, "LGA"] = "Gbagada"

In [33]:
for i in range(0, data.shape[0], 4):
    data.loc[i : i+3, 'LGA'] = data.loc[i,'LGA']

In [34]:
data

,LGA,No_of_bedrooms,Q1_2016,Q2_2016,Q3_2016,Q4 - 2016 (N),Q1_2017,Q2_2017,Q3_2017,Q4_2017,index_Q1_2016,index_Q2_2016,index_Q3_2016,index_Q4_2016,index_Q1_2017,index_Q2_2017,index_Q3_2017,index_Q4_2017,price_change_Q2_2016,price_change_Q3_2016,price_change_Q4_2016,price_change_Q1_2017,price_change_Q2_2017,price_change_Q3_2017,price_change_Q4_2017
0,Agege,5 Bedroom,4.397350e+07,4.150000e+07,4.125000e+07,4.211764e+07,3.850000e+07,34000000.0,3.405556e+07,3.150000e+07,100.0,94.375021,93.806497,95.779592,87.552731,77.319295,77.445632,71.634052,-5.624979,-0.602410,2.103367,-8.589368,-11.688312,0.163397,-7.504077
1,Agege,4 Bedroom,3.750000e+07,3.800000e+07,3.745000e+07,3.850000e+07,2.750000e+07,25500000.0,2.603356e+07,2.603356e+07,100.0,101.333333,99.866667,102.666667,73.333333,68.000000,69.422813,69.422813,1.333333,-1.447368,2.803738,-28.571429,-7.272727,2.092373,0.000000
2,Agege,3 Bedroom,1.932000e+07,1.875000e+07,1.750000e+07,1.757550e+07,1.600000e+07,16655000.0,1.665500e+07,1.573899e+07,100.0,97.049689,90.579710,90.970497,82.815735,86.206004,86.206004,81.464742,-2.950311,-6.666667,0.431429,-8.964183,4.093750,0.000000,-5.499921
3,Agege,2 Bedroom,1.163458e+07,1.078623e+07,9.937875e+06,9.574290e+06,8.483553e+06,8975500.0,8.255555e+06,7.348489e+06,100.0,92.708335,85.416669,82.291633,72.916679,77.144995,70.957022,63.160731,-7.291665,-7.865167,-3.658579,-11.392354,5.798832,-8.021224,-10.987343
4,Ajah,5 Bedroom,4.430709e+07,3.500000e+07,3.900000e+07,5.000000e+07,5.500000e+07,53565500.0,5.283333e+07,5.200000e+07,100.0,78.994135,88.022036,112.848764,124.133640,120.896009,119.243526,117.362714,-21.005865,11.428571,28.205128,10.000000,-2.608182,-1.366863,-1.577286
5,Ajah,4 Bedroom,3.631651e+07,2.654300e+07,3.300000e+07,3.500000e+07,3.150000e+07,32450500.0,3.910000e+07,4.150000e+07,100.0,73.087962,90.867752,96.374889,86.737400,89.354667,107.664519,114.273082,-26.912038,24.326564,6.060606,-10.000000,3.017460,20.491210,6.138107
6,Ajah,3 Bedroom,2.663946e+07,2.200000e+07,2.750000e+07,3.000000e+07,2.166667e+07,21950500.0,2.946667e+07,3.150000e+07,100.0,82.584269,103.230336,112.614912,81.332993,82.398454,110.612871,118.245658,-17.415731,25.000000,9.090909,-27.777777,1.309998,34.241439,6.900451
7,Ajah,2 Bedroom,1.685837e+07,1.617027e+07,1.445003e+07,1.634230e+07,1.552518e+07,16435500.0,2.350000e+07,2.400000e+07,100.0,95.918367,85.714286,96.938776,92.091837,97.491636,139.396639,142.362524,-4.081633,-10.638298,13.095238,-5.000000,5.863494,42.983177,2.127660
8,Gbagada,5 Bedroom,5.160000e+07,4.534550e+07,6.500000e+07,7.000000e+07,8.125000e+07,78365550.0,6.225000e+07,6.225000e+07,100.0,87.878876,125.968992,135.658915,157.461240,151.871221,120.639535,120.639535,-12.121124,43.343882,7.692308,16.071429,-3.550092,-20.564585,0.000000
9,Gbagada,4 Bedroom,5.000000e+07,4.150000e+07,4.250000e+07,5.500000e+07,6.125000e+07,63255500.0,6.325550e+07,6.325550e+07,100.0,83.000000,85.000000,110.000000,122.500000,126.511000,126.511000,126.511000,-17.000000,2.409639,29.411765,11.363636,3.274286,0.000000,0.000000
10,Gbagada,3 Bedroom,3.386667e+07,2.500000e+07,3.000000e+07,3.150000e+07,2.975000e+07,34750000.0,3.000000e+07,3.050000e+07,100.0,73.818897,88.582676,93.011810,87.844487,102.608267,88.582676,90.059054,-26.181103,20.000000,5.000000,-5.555556,16.806723,-13.669065,1.666667
11,Gbagada,2 Bedroom,2.169545e+07,2.009684e+07,1.909200e+07,1.832832e+07,1.887504e+07,20666667.0,2.066667e+07,2.250000e+07,100.0,92.631579,88.000000,84.480000,87.000000,95.258053,95.258053,103.708362,-7.368421,-5.000000,-4.000000,2.982955,9.492015,0.000000,8.870966
12,Ibeju-Lekki,5 Bedroom,4.500000e+07,4.600000e+07,4.100000e+07,4.100000e+07,3.850000e+07,40450667.0,4.016667e+07,4.016667e+07,100.0,102.222222,91.111111,91.111111,85.555556,89.890371,89.259260,89.259260,2.222222,-10.869565,0.000000,-6.097561,5.066668,-0.702090,0.000000
13,Ibeju-Lekki,4 Bedroom,3.060000e+07,3.350000e+07,3.766667e+07,3.500000e+07,3.125000e+07,33465500.0,3.216667e+07,3.000000e+07,100.0,109.477124,123.093683,114.379085,102.124183,109.364379,105.119827,98.039216,9.477124,12.437812,-7.079647,-10.714286,7.089600,-3.881110,-6.735752
14,Ibeju-Lekki,3 Bedroom,2.234210e+07,2.500000e+07,1.690000e+07,2.266569e+07,2.212278e+07,22325450.0,2.150000e+07,NaN,100.0,111.896350,75.641933,61.766785,55.948175,61.567610,96.230861,0.000000,11.896350,-32.400000,-18.343195,-9.420290,10.044000,-3.697350,-100.000000
15,Ibeju-Lekki,2 Bedroom,2.427117e+07,2.067395e+07,1.964025e+07,1.380000e+07,1.250000e+07,13755500.0,1.100000e+07,1.000000e+07,100.0,85.179011,80.920061,93.385234,91.148364,91.983398,45.321253,41.201139,-14.820989,-5.000000,15.404305,-2.395314,0.916125,-20.031987,-9.090909
16,Ikeja,5 Bedroom,1.116725e+08,1.450000e+08,1.550000e+08,1.372242e+08,1.216642e+08,119450500.0,1.216667e+08,1.200000e+08,100.0,129.843923,138.798676,122.880866,108.947270,106.964976,108.949499,107.457039,29.843923,6.896552,-11.468272,-11.339110,-1.819499,1.855302,-1.369863
17,Ikeja,4 Bedroom,7.500000e+07,5.650000e+07,6.500000e+07,6.550000e+07,6.500000e+07,71667000.0,7.916667e+07,7.924238e+07,100.0,75.333333,86.666667,87.333333,86.666667,95.556000,105.555556,105.656513,-24.666667,15.044248,0.769231,-0.763359,10.256923,10.464603,0.095643
18,Ikeja,3 Bedroom,4.347222e+07,4.425000e+07,4.000000e+07,4.500000e+07,3.750000e+07,46750000.0,3.791667e+07,3.995293e+07,100.0,101.789138,92.012780,103.514378,86.261981,107.539937,87.220448,91.904508,1.789138,-9.604520,12.500000,-16.666667,24.666667,-18.894830,5.370369
19,Ikeja,2 Bedroom,2.618163e+07,2.454528e+07,2.427255e+07,2.173075e+07,2.146265e+07,21695345.0,2.291667e+07,2.393858e+07,100.0,93.750000,92.708333,83.000000,81.976000,82.864757,87.529558,91.432746,-6.250000,-1.111111,-10.471910,-1.233735,1.084168,5.629415,4.459280
20,Ikoyi,5 Bedroom,2.276842e+08,1.650000e+08,3.150000e+08,3.250000e+08,2.750000e+08,260000000.0,2.938333e+08,2.991144e+08,100.0,72.468793,138.349514,142.741562,120.781322,114.193250,129.053012,131.372467,-27.531207,90.909091,3.174603,-15.384615,-5.454545,13.012820,1.797288
21,Ikoyi,4 Bedroom,1.537273e+08,1.500000e+08,2.000000e+08,1.625000e+08,1.350000e+08,182750000.0,2.166667e+08,2.168739e+08,100.0,97.575399,130.100532,105.706682,87.817859,118.879361,140.942243,141.077045,-2.424601,33.333333,-18.750000,-16.923077,35.370370,18.559052,0.095643
22,Ikoyi,3 Bedroom,1.279221e+08,1.300000e+08,1.750000e+08,1.850000e+08,1.625000e+08,155000000.0,1.383333e+08,1.384656e+08,100.0,101.624365,136.802030,144.619289,127.030457,121.167513,108.138748,108.242175,1.624365,34.615385,5.714286,-12.162162,-4.615385,-10.752688,0.095643
23,Ikoyi,2 Bedroom,1.040016e+08,1.016026e+08,9.864326e+07,9.215000e+07,9.407500e+07,96500000.0,9.416667e+07,9.425673e+07,100.0,97.693300,94.847864,88.604439,90.455372,92.787068,90.543512,90.630111,-2.306700,-2.912621,-6.582568,2.088985,2.577731,-2.417962,0.095643
24,Isolo,5 Bedroom,5.796875e+07,5.000000e+07,5.575000e+07,5.300000e+07,4.800000e+07,49005500.0,4.900550e+07,4.840032e+07,100.0,86.253369,96.172507,91.428571,82.803235,84.537790,84.537790,83.493806,-13.746631,11.500000,-4.932735,-9.433962,2.094792,0.000000,-1.234931
25,Isolo,4 Bedroom,3.671429e+07,3.850000e+07,3.800000e+07,4.000000e+07,3.500000e+07,35975555.0,3.597556e+07,3.600996e+07,100.0,104.863812,103.501945,108.949415,95.330739,97.987892,97.987892,98.081611,4.863812,-1.298701,5.263158,-12.500000,2.787300,0.000000,0.095643
26,Isolo,3 Bedroom,4.000000e+07,3.250000e+07,3.500000e+07,3.500000e+07,3.150000e+07,32045500.0,3.233333e+07,3.236426e+07,100.0,81.250000,87.500000,87.500000,78.750000,80.113750,80.833332,80.910644,-18.750000,7.692308,0.000000,-10.000000,1.731746,0.898201,0.095643
27,Isolo,2 Bedroom,1.665409e+07,1.606025e+07,1.429362e+07,1.415598e+07,1.325000e+07,12155000.0,1.270534e+07,1.271750e+07,100.0,96.434216,85.826452,85.000000,79.560014,72.985055,76.289617,76.362583,-3.565784,-11.000000,-0.962934,-6.399983,-8.264151,4.527725,0.095643
28,Lekki,5 Bedroom,6.936753e+07,6.500000e+07,9.750000e+07,7.955566e+07,7.566667e+07,78500000.0,8.245050e+07,8.301327e+07,100.0,93.703781,140.555671,114.687165,109.080812,113.165335,118.860363,119.671645,-6.296219,50.000000,-18.404455,-4.888388,3.744493,5.032484,0.682551
29,Lekki,4 Bedroom,5.000000e+07,5.500000e+07,6.250000e+07,6.570567e+07,5.850000e+07,50000000.0,5.300500e+07,5.400966e+07,100.0,110.000000,125.000000,131.411334,117.000000,100.000000,106.010000,108.019314,10.000000,13.636364,5.129067,-10.966584,-14.529915,6.010000,1.895400
30,Lekki,3 Bedroom,3.466848e+07,3.750000e+07,3.750000e+07,3.555568e+07,3.400000e+07,40000000.0,4.266667e+07,4.347537e+07,100.0,108.167425,108.167425,102.559088,98.071799,115.378587,123.070494,125.403172,8.167425,0.000000,-5.184867,-4.375321,17.647059,6.666667,1.895400
31,Lekki,2 Bedroom,2.258166e+07,2.167839e+07,2.111831e+07,2.098834e+07,2.053141e+07,20975555.0,2.340500e+07,2.384862e+07,100.0,96.000000,93.519753,92.944174,90.920730,92.887570,103.646057,105.610564,-4.000000,-2.583591,-0.615463,-2.177053,2.163246,11.582268,1.895400
32,Magodo,5 Bedroom,9.719008e+07,8.000000e+07,1.100000e+08,9.916667e+07,8.350000e+07,85050500.0,9.208333e+07,9.417140e+07,100.0,82.312925,113.180272,102.033730,85.914115,87.509443,94.745606,96.894047,-17.687075,37.500000,-9.848485,-15.798320,1.856886,8.269008,2.267589
33,Magodo,4 Bedroom,6.416346e+07,5.300000e+07,6.250000e+07,6.133333e+07,5.750000e+07,60666667.0,5.671625e+07,5.877050e+07,100.0,82.601528,97.407462,95.589189,89.614865,94.550177,88.393376,91.594957,-17.398472,17.924528,-1.866667,-6.249999,5.507247,-6.511676,3.621970
34,Magodo,3 Bedroom,4.500000e+07,4.100000e+07,4.000000e+07,4.000000e+07,3.666667e+07,38025000.0,3.057592e+07,3.360516e+07,100.0,91.111111,88.888889,88.888889,81.481482,84.500000,67.946482,74.678135,-8.888889,-2.439024,0.000000,-8.333332,3.704545,-19.589962,9.907287
35,Magodo,2 Bedroom,2.722150e+07,2.418479e+07,2.415460e+07,2.171200e+07,2.089780e+07,21050500.0,2.231250e+07,2.533384e+07,100.0,88.844455,88.733538,79.760483,76.769466,77.330419,81.966460,93.065556,-11.155545,-0.124844,-10.112360,-3.749999,0.730698,5.995107,13.541021
36,Maryland,5 Bedroom,1.077419e+08,1.070000e+08,1.200000e+08,1.300000e+08,1.193333e+08,121650500.0,1.233333e+08,1.194513e+08,100.0,99.311378,111.377246,120.658683,110.758483,112.909147,114.471058,110.867967,-0.688622,12.149533,8.333333,-8.205128,1.941760,1.383334,-3.147600
37,Maryland,4 Bedroom,7.702703e+07,7.750000e+07,6.000000e+07,6.000000e+07,5.366667e+07,54250500.0,5.418750e+07,5.623933e+07,100.0,100.614035,77.894737,77.894737,69.672515,70.430474,70.348684,73.012459,0.614035,-22.580645,0.000000,-10.555555,1.087888,-0.116128,3.786531
38,Maryland,3 Bedroom,3.500000e+07,3.550000e+07,3.500000e+07,3.300000e+07,3.200000e+07,34465500.0,3.500000e+07,3.503348e+07,100.0,101.428571,100.000000,94.285714,91.428571,98.472857,100.000000,100.095643,1.428571,-1.408451,-5.714286,-3.030303,7.704688,1.550826,0.095643
39,Maryland,2 Bedroom,2.149150e+07,2.054228e+07,1.989792e+07,2.042894e+07,2.063738e+07,21005000.0,2.100500e+07,2.102509e+07,100.0,95.583269,92.585069,95.055910,96.025758,97.736314,97.736314,97.829793,-4.416731,-3.136742,2.668725,1.020293,1.781351,0.000000,0.095643
40,Ojodu,5 Bedroom,6.347826e+07,6.375000e+07,6.400000e+07,6.583333e+07,5.150000e+07,54455555.0,5.000000e+07,5.004782e+07,100.0,100.428082,100.821918,103.710045,81.130137,85.786148,78.767123,78.842459,0.428082,0.392157,2.864583,-21.772152,5.738942,-8.182003,0.095643
41,Ojodu,4 Bedroom,4.500000e+07,4.450000e+07,4.600000e+07,5.033333e+07,4.250000e+07,43765500.0,4.050000e+07,4.053874e+07,100.0,98.888889,102.222222,111.851851,94.444444,97.256667,90.000000,90.086079,-1.111111,3.370787,9.420289,-15.562913,2.977647,-7.461357,0.095643
42,Ojodu,3 Bedroom,3.000000e+07,3.250000e+07,3.000000e+07,3.150000e+07,3.000000e+07,31665500.0,3.533333e+07,3.536713e+07,100.0,108.333333,100.000000,105.000000,100.000000,105.551667,117.777777,117.890423,8.333333,-7.692308,5.000000,-4.761905,5.551667,11.583057,0.095643
43,Ojodu,2 Bedroom,1.918566e+07,1.959735e+07,1.792583e+07,1.738806e+07,1.686642e+07,17656667.0,1.966667e+07,1.968548e+07,100.0,102.145803,93.433488,90.630483,87.911568,92.030526,102.507099,102.605140,2.145803,-8.529293,-3.000000,-3.000000,4.685342,11.383802,0.095643
44,Surulere,5 Bedroom,6.000000e+07,5.250000e+07,6.333333e+07,6.766667e+07,6.500000e+07,65875500.0,6.200000e+07,6.298488e+07,100.0,87.500000,105.555555,112.777778,108.333333,109.792500,103.333333,104.974800,-12.500000,20.634920,6.842106,-3.940887,1.346923,-5.883067,1.588517
45,Surulere,4 Bedroom,4.553846e+07,4.850000e+07,3.750000e+07,4.055000e+07,5.333333e+07,54765500.0,5.241667e+07,5.315405e+07,100.0,106.503377,82.347972,89.045607,117.117115,120.262076,115.104166,116.723422,6.503377,-22.680412,8.133333,31.524866,2.685313,-4.288892,1.406775
46,Surulere,3 Bedroom,3.333333e+07,3.750000e+07,4.000000e+07,3.066667e+07,3.550000e+07,35950000.0,3.516667e+07,3.666456e+07,100.0,112.500001,120.000001,92.000002,106.500001,107.850001,105.500002,109.993691,12.500001,6.666667,-23.333333,15.760868,1.267606,-2.178951,4.259421
47,Surulere,2 Bedroom,1.922417e+07,1.934054e+07,1.988946e+07,1.980604e+07,1.903514e+07,19666667.0,2.075000e+07,2.005757e+07,100.0,100.605358,103.460715,103.026782,99.016699,102.301793,107.937059,104.335204,0.605358,2.838175,-0.419418,-3.892272,3.317717,5.508473,-3.336996
48,Victoria Island,5 Bedroom,1.410000e+08,1.271389e+08,1.146667e+08,1.257500e+08,1.196667e+08,131750000.0,1.374167e+08,1.375481e+08,100.0,90.169425,81.323877,89.184397,84.869977,93.439716,97.458629,97.551842,-9.830575,-9.809919,9.665697,-4.837641,10.097493,4.301076,0.095643
49,Victoria Island,4 Bedroom,9.500000e+07,1.050000e+08,1.425000e+08,1.500000e+08,1.233333e+08,95000000.0,1.105000e+08,1.106057e+08,100.0,110.526316,150.000000,157.894737,129.824561,100.000000,116.315789,116.427038,10.526316,35.714286,5.263158,-17.777778,-22.972973,16.315789,0.095643
50,Victoria Island,3 Bedroom,6.500000e+07,6.500000e+07,7.500000e+07,7.756750e+07,6.250000e+07,73750000.0,6.804833e+07,6.811342e+07,100.0,100.000000,115.384615,119.334615,96.153846,113.461538,104.689743,104.789872,0.000000,15.384615,3.423333,-19.425017,18.000000,-7.731074,0.095643
51,Victoria Island,2 Bedroom,3.520000e+07,3.941720e+07,3.737500e+07,3.509700e+07,3.130138e+07,33450550.0,3.470833e+07,3.474153e+07,100.0,111.980682,106.178977,99.707386,88.924375,95.029972,98.603219,98.697526,11.980682,-5.180987,-6.094983,-10.814657,6.866055,3.760127,0.095643
52,Yaba,5 Bedroom,7.000000e+07,6.700000e+07,6.600000e+07,6.150000e+07,6.150000e+07,62955000.0,6.295500e+07,6.301521e+07,100.0,95.714286,94.285714,87.857143,87.857143,89.935714,89.935714,90.021732,-4.285714,-1.492537,-6.818182,0.000000,2.365854,0.000000,0.095643
53,Yaba,4 Bedroom,6.000000e+07,5.700000e+07,6.000000e+07,6.250000e+07,5.350000e+07,55450500.0,5.916667e+07,5.922326e+07,100.0,95.000000,100.000000,104.166667,89.166667,92.417500,98.611112,98.705427,-5.000000,5.263158,4.166667,-14.400000,3.645794,6.701774,0.095643
54,Yaba,3 Bedroom,4.544444e+07,3.000000e+07,4.200000e+07,4.055600e+07,3.733333e+07,38550555.0,4.250000e+07,4.254065e+07,100.0,66.014671,92.420539,89.243033,82.151589,84.830073,93.520783,93.610230,-33.985329,40.000000,-3.438095,-7.946215,3.260416,10.244846,0.095643
55,Yaba,2 Bedroom,2.370743e+07,2.204791e+07,1.991424e+07,2.183227e+07,2.199065e+07,22765650.0,2.425000e+07,2.427319e+07,100.0,93.000000,84.000000,92.090439,92.758490,96.027508,102.288627,102.386459,-7.000000,-9.677419,9.631474,0.725430,3.524225,6.520130,0.095643
56,ALL CITIES,5 Bedroom,8.822491e+07,5.400000e+07,6.800000e+07,6.400000e+07,6.800000e+07,71663667.0,7.474164e+07,7.581312e+07,100.0,61.207202,77.075736,72.541869,77.075736,81.228380,84.717157,85.931650,-38.792798,25.925926,-5.882353,6.250000,5.387746,4.295022,1.433586
57,ALL CITIES,4 Bedroom,5.931324e+07,4.900000e+07,4.500000e+07,4.700000e+07,4.600000e+07,48755550.0,5.010441e+07,5.115233e+07,100.0,82.612248,75.868391,79.240319,77.554355,82.200114,84.474249,86.241007,-17.387752,-8.163265,4.444444,-2.127660,5.990326,2.766583,2.091475
58,ALL CITIES,3 Bedroom,4.637588e+07,3.100000e+07,3.000000e+07,3.300000e+07,3.300000e+07,35250500.0,3.645863e+07,3.849350e+07,100.0,66.845088,64.688795,71.157675,71.157675,76.010413,78.615490,83.003267,-33.154912,-3.225806,10.000000,0.000000,6.819697,3.427264,5.581313
59,ALL CITIES,2 Bedroom,1.874957e+07,1.815368e+07,1.852910e+07,1.778937e+07,1.716504e+07,17944556.0,1.814790e+07,1.816526e+07,100.0,96.821820,98.824139,94.878779,91.548955,95.706480,96.791032,96.883606,-3.178180,2.068046,-3.992304,-3.509556,4.541313,1.133206,0.095643

#### Check the columns with missing values again

In [45]:
missing_data = data.columns[data.isnull().any()].tolist()

In [46]:
print(*missing_data, sep ='\n')

Q4_2017

#### Check the row with missing values

In [66]:
data[data['Q4_2017'] == float("NaN")]

Empty DataFrame
Columns: [LGA, No_of_bedrooms, Q1_2016, Q2_2016, Q3_2016, Q4_2016, Q1_2017, Q2_2017, Q3_2017, Q4_2017, index_Q1_2016, index_Q2_2016, index_Q3_2016, index_Q4_2016, index_Q1_2017, index_Q2_2017, index_Q3_2017, index_Q4_2017, price_change_Q2_2016, price_change_Q3_2016, price_change_Q4_2016, price_change_Q1_2017, price_change_Q2_2017, price_change_Q3_2017, price_change_Q4_2017]
Index: []

In [69]:
float(data.loc[14,'Q4_2017'])

nan